apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: alpine-sfc
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.serviceDaemonSet.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.serviceDaemonSet.annotations }}
      {{- with .Values.serviceDaemonSet.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      labels:
        app.kubernetes.io/name: alpine-sfc
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.serviceDaemonSet.labels }}
        {{- with .Values.serviceDaemonSet.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      containers:
        - name: alpine
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: {{ toJson .Values.worker.command }}
          args: {{ toJson .Values.worker.args }}
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      hostNetwork: false
      dnsPolicy: ClusterFirst
